#!/usr/bin/env bash
set -euo pipefail

if [[ $# -lt 2 || $# -gt 3 ]]; then
  cat <<'EOF'
Usage:
  bash rsync_concat_transfer.sh <riboseq_dir> <destination_dir> [--dry-run]

Example:
  bash rsync_concat_transfer.sh \
    /home/jiye/jiye/darkproteome/data/RPFdb/kidney/Riboseq \
    user@host:/data/RPFdb_transfer/kidney_riboseq_concat \
    --dry-run

This script expects the following files generated by make_concat_transfer_lists.py:
  <riboseq_dir>/fastq/concat_transfer_lists/concat_component_raw_fastq_paths.txt
  <riboseq_dir>/fastq/concat_transfer_lists/concat_finalfastq_forbam_GSM_paths.txt

Behavior:
  1. rsync raw SRR FASTQ components to <destination_dir>/raw_fastq_concat_components
  2. rsync finalfastq_forbam_GSM files to <destination_dir>/finalfastq_forbam_GSM_concat_targets
     using -L so symlinks are dereferenced and real FASTQ files are copied.
EOF
  exit 1
fi

RIBOSEQ_DIR="$(python3 -c 'from pathlib import Path; import sys; print(Path(sys.argv[1]).expanduser().resolve())' "$1")"
DEST_DIR="$2"
DRY_RUN="${3:-}"

FASTQ_DIR="$RIBOSEQ_DIR/fastq"
FINAL_GSM_DIR="$FASTQ_DIR/finalfastq_forbam_GSM"
LIST_DIR="$FASTQ_DIR/concat_transfer_lists"

RAW_LIST="$LIST_DIR/concat_component_raw_fastq_paths.txt"
FINAL_LIST="$LIST_DIR/concat_finalfastq_forbam_GSM_paths.txt"

TMP_DIR="$LIST_DIR/.rsync_tmp"
RAW_REL_LIST="$TMP_DIR/concat_component_raw_fastq_paths.relative.txt"
FINAL_REL_LIST="$TMP_DIR/concat_finalfastq_forbam_GSM_paths.relative.txt"

RAW_DEST="$DEST_DIR/raw_fastq_concat_components"
FINAL_DEST="$DEST_DIR/finalfastq_forbam_GSM_concat_targets"

mkdir -p "$TMP_DIR"

if [[ ! -f "$RAW_LIST" ]]; then
  echo "Missing raw list: $RAW_LIST" >&2
  exit 1
fi

if [[ ! -f "$FINAL_LIST" ]]; then
  echo "Missing final GSM list: $FINAL_LIST" >&2
  exit 1
fi

if [[ ! -d "$FASTQ_DIR" ]]; then
  echo "Missing fastq dir: $FASTQ_DIR" >&2
  exit 1
fi

if [[ ! -d "$FINAL_GSM_DIR" ]]; then
  echo "Missing finalfastq_forbam_GSM dir: $FINAL_GSM_DIR" >&2
  exit 1
fi

python3 - "$FASTQ_DIR" "$RAW_LIST" "$RAW_REL_LIST" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1]).resolve()
input_list = Path(sys.argv[2])
output_list = Path(sys.argv[3])

lines = []
for raw_line in input_list.read_text(encoding="utf-8").splitlines():
    path_text = raw_line.strip()
    if not path_text:
        continue
    path = Path(path_text).expanduser().resolve(strict=False)
    try:
        rel = path.relative_to(root)
    except ValueError as exc:
        raise SystemExit(f"Raw path is outside fastq dir: {path}") from exc
    lines.append(str(rel))

output_list.write_text("".join(f"{line}\n" for line in lines), encoding="utf-8")
PY

python3 - "$FINAL_GSM_DIR" "$FINAL_LIST" "$FINAL_REL_LIST" <<'PY'
from pathlib import Path
import sys

root = Path(sys.argv[1]).resolve()
input_list = Path(sys.argv[2])
output_list = Path(sys.argv[3])

lines = []
for raw_line in input_list.read_text(encoding="utf-8").splitlines():
    path_text = raw_line.strip()
    if not path_text:
        continue
    path = Path(path_text).expanduser().resolve(strict=False)
    try:
        rel = path.relative_to(root)
    except ValueError as exc:
        raise SystemExit(f"Final GSM path is outside finalfastq_forbam_GSM dir: {path}") from exc
    lines.append(str(rel))

output_list.write_text("".join(f"{line}\n" for line in lines), encoding="utf-8")
PY

RSYNC_FLAGS=(-avh --info=progress2)
if [[ "$DRY_RUN" == "--dry-run" ]]; then
  RSYNC_FLAGS+=(--dry-run)
fi

echo "Riboseq dir: $RIBOSEQ_DIR"
echo "Fastq dir: $FASTQ_DIR"
echo "Final GSM dir: $FINAL_GSM_DIR"
echo "List dir: $LIST_DIR"
echo "Destination root: $DEST_DIR"
echo "Raw destination: $RAW_DEST"
echo "Final GSM destination: $FINAL_DEST"
echo "Raw relative list: $RAW_REL_LIST"
echo "Final relative list: $FINAL_REL_LIST"
echo
echo "Running raw FASTQ rsync..."
rsync "${RSYNC_FLAGS[@]}" \
  --files-from="$RAW_REL_LIST" \
  "$FASTQ_DIR"/ \
  "$RAW_DEST"/

echo
echo "Running final GSM FASTQ rsync with symlink dereference (-L)..."
rsync "${RSYNC_FLAGS[@]}" -L \
  --files-from="$FINAL_REL_LIST" \
  "$FINAL_GSM_DIR"/ \
  "$FINAL_DEST"/

echo
echo "Done."
